### ISSUE TITLE
Feature request: exact definition of directional error

### ISSUE THREAD

**Issue by cwjames1983** [chime-frb-open-data/community#18]
The CHIME FRB catalog quotes an error in ra and dec. Somewhere, it should be specified if this is a 1 sigma, 90%, etc error.

## Expected Behavior

The parameter definition here:
https://www.chime-frb.ca/analysis
should specify this, i.e. 1 sigma, 90% error etc

## Current Behavior

No such value is specified

## Possible Solution

Add a quick note to the above page to specify the definition of 'error'.

## Steps to Reproduce (for bugs)

1. Go to https://www.chime-frb.ca/analysis

## Context

We are trying to publish a paper using CHIME data, and need to be specific about the localisation error. We are uncertain as to what values are quoted, and find it difficult to proceed with a possible host galaxy association.

## Your Environment

* Python Version:
* Environment name and version (e.g. Chrome 39,):
* Operating System and version (desktop or mobile):
* Link to your project:
Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by shinybrar** [comment]
@cwjames1983 This seems like a simple request -- @chitrangpatel I am going to assign you to investigate it further.

**Comment by cwjames1983** [comment]
I see this has now been done, with 68% being added. Thanks! I am closing this now.
