### ISSUE TITLE
Catalog 1 Not Loading

### ISSUE THREAD

**Issue by emilyh1701** [chime-frb-open-data/community#34]
For the past few days catalog 1 will not load. I have tried different web browsers and different computers to see if it was an issue with my computer and it is not. What is the reason catalog 1 will no longer show up?

**Comment by 0xCoto** [comment]
Can confirm this is also what I see:

![screenshot](https://user-images.githubusercontent.com/25392776/137593315-bdba37c7-cb41-4151-8210-83808768f930.png)

Looks like there is a `500` error. Here's the error displayed in the console above in case it helps the sysadmins debug the issue:
```js
> POST https://catalog.chime-frb.ca/authorize 500
> Uncaught (in promise) 
t {url: 'https://catalog.chime-frb.ca/authorize', ok: false, status: 500, statusText: '', headers: t, …}
body:
description: "Internal Server Error"
message: "The server encountered an internal error and cannot complete your request."
status: 500
[[Prototype]]: Object
bodyText: "{\"description\":\"Internal Server Error\",\"status\":500,\"message\":\"The server encountered an internal error and cannot complete your request.\"}"
headers: t
map: {content-length: Array(1), content-type: Array(1)}
[[Prototype]]: Object
ok: false
status: 500
statusText: ""
url: "https://catalog.chime-frb.ca/authorize"
data: (...)
[[Prototype]]: Object
```

**Comment by chitrangpatel** [comment]
This is now fixed. If you're satisfied, please close this issue.

**Comment by 0xCoto** [comment]
@chitrangpatel ~~Now getting a 404 — Not Found error.~~

**Edit:** Looks like I had to use `https://www.` instead of `http://`. Might want to consider forcing HTTPS for greater accessibility.
