### ISSUE TITLE
Is the alert system down now?

### ISSUE THREAD

**Issue by yniino** [chime-frb-open-data/community#74]
I have been receiving CHIME/FRB alerts via VOEvents and email, but the both streams seem to be down since last week. The last event alert I received is "ivo://ca.chimenet.frb/FRB-DETECTION-#2022-11-19-02:12:43.164293UTC+0000_ae104a28a784", and the last test alert is "ivo://azwaniga/test#TestEvent-2022-11-22T15:10:07Z". 

Is anyone receiving alerts now? Did I overlooked an announcement of a maintenance work?

**Comment by emilypetroff** [comment]
Hello, yes the system is down. Apologies for the lack of alert. The compute system underwent some maintenance and the system recover time has stretched longer than expected. An announcement was not posted, but I will put one up now. Apologies for the inconvenience!

**Comment by yniino** [comment]
Thank you for the confirmation. I will be waiting for the alerting is resumed.

**Comment by emilypetroff** [comment]
The service has resumed, your broker should now also be subscribed to the Comet broker sending FRB VOEvents from CHIME.

**Comment by yniino** [comment]
Thank you for handling this. I have confirmed the alerting has resumed.
