### ISSUE TITLE
-

### ISSUE THREAD

**Issue by 0xCoto** [chime-frb-open-data/community#78]

**Comment by zpleunis** [comment]
Hi Apostolos,

Sorry for the slow reply: the catalog contains multiple widths. There's the intrinsic width of subbursts that has fitted out dispersion smearing and scattering, which is under the `width_fitb` column, and there's a measure of the the duration of the full burst envelope under `bc_width` that has been calculated from convolving the dedispersed time-series with tophat (boxcar) functions and finding the width of the boxcar that gives the highest signal-to-noise (see reference here: https://www.chime-frb.ca/analysis). 

Best,
Ziggy
