### ISSUE TITLE
Checking the spatial position of the observer's meridian at the time of registration of repeated FRBs (10 outliers)

### ISSUE THREAD

**Issue by IvanKrasnyj** [chime-frb-open-data/community#83]
I calculated the positions of the CHIME zenith point at the times of registration of repeated FRBs and found about 8 outliers in which the right ascension of the zenith point of the telescope differs from the rest points by about 180 degrees (also, in two cases - by about 30 and 100 degrees). How can this be with a transit telescope having a fairly narrow beam pattern?

[Zenith points for repeated FRBs](https://github.com/IvanKrasnyj/Skyfield-exploration/blob/main/CHIME_FRB_zenith_points.xlsx )

## Expected Behavior
FRB registration occurs when an object enters the telescope beam. In this case, the FRB declination circle is aligned with the meridian of the observer (telescope). In other words, at the time of registration, the right ascension of the zenith point of the telescope cannot differ from the right ascension of the observed FRB by more than half the beam width.

**Comment by zpleunis** [comment]
Hi @IvanKrasnyj,

Indeed the peak sensitivity of the CHIME telescope is toward a narrow 1--2-degree strip on the meridian, but the telescope has quite a bit of sensitivity through the "sidelobes" of the beams, which makes us sensitive to bright bursts that occur up to a few tens of degrees away from the meridian. This is for example how we detected a bright burst from Galactic magnetar SGR 1935+2154 (https://ui.adsabs.harvard.edu/abs/2020Natur.587...54C/abstract). We sometimes even detect giant pulses from the Crab pulsar when that source is near our horizon! You can see some examples of our model of our beams in Figures 2 and 3 in the paper describing the first CHIME/FRB FRB catalog (https://ui.adsabs.harvard.edu/abs/2021ApJS..257...59C/abstract). 

This could explain meridian offsets of a few to a few tens degrees. For the 30 and 100 degree offset, it could be that these are very bright bursts detected in sidelobes, or they could be spurious associations to the repeating sources.

As for the 180 degree offsets you see: CHIME is located at a latitude approximately 49 degrees North and CHIME/FRB observes from -60 to +60 degrees in the North-South direction. This means that all sources with declinations >~ 71 degrees transit through the beams of the telescope twice per sidereal day, on two sides of the North Celestial Pole. We call the two transits the "upper" and "lower" transit, with the upper transit going through the more sensitive part of the beam. 

Best,
Ziggy

**Comment by IvanKrasnyj** [comment]
Hello, @zpleunis,

Thanks for the clarification, Ziggy. You are right. Only 5 out of 21 repeated FRBs have a DEC > 71 degrees, and three of them have been noted by me. So one can also expect a "lower" transit for FRB20180908B and FRB20190209A if that ever happens.
