### ISSUE TITLE
CHIME/FRB Repeater Catalog downloading problem

### ISSUE THREAD

**Issue by spaceinmind** [chime-frb-open-data/community#85]
Dear CHIME team,

I tried to download the CHIME/FRB Repeater Catalog from the recent data release [[https://www.chime-frb.ca/repeater_catalog](https://www.chime-frb.ca/repeater_catalog)]

When I tried to download the Repeater Catalog Files and the Pre-Repeater Catalog Files, the two catalogs looked the same. I tried downloading .csv, and .fits and the same thing happened.

Could you help me to check it? Or, is there any way I can download the actual Repeater Catalog Files and the Pre-Repeater Catalog Files?
Thank you very much.

Best regards,
Simon Ho

**Comment by zpleunis** [comment]
Dear Simon,

Thank you for your bug report. This is a known issue and will be fixed in the next few days.

Best,
Ziggy

**Comment by Bkarimi1970** [comment]
Hello Ziggy,
Hope you are doing well. I want to start to work with FRBs data taken from CHIME. I need to know where should start? Please help me out with this.
Regards,
Bahman

**Comment by SiqiLiu43** [comment]
Hi @spaceinmind , apologies for the delay in reply, the issue has been fixed since April 20; please don't hesitate to let me know if you still have trouble accessing the data :)

**Comment by Bkarimi1970** [comment]
Thank you so much.
Regards,
Bahman

**Comment by SiqiLiu43** [comment]
Hi @Bkarimi1970 , thanks for your interest in CHIME/FRB data! I recommend starting a new [discussion thread](https://github.com/chime-frb-open-data/community/discussions) with some context on your specific application so our science team can provide more effective assistance. If you ever encounter issues/bugs while accessing our data, feel free to open an issue [here](https://github.com/chime-frb-open-data/community/issues).
