### ISSUE TITLE
Ask about CHIME maintenance times

### ISSUE THREAD

**Issue by frbliaker** [chime-frb-open-data/community#87]
Recently when I am working on repeat FRB, I need to use the observation time of the source to calculate the event rate. Here, I consider subtracting the first burst observation from the last burst observation and also subtracting the time that you spent shutting down the equipment (including maintenance, etc.). Therefore, I would like to ask if it is possible to provide me with such a time record. Because I have only recently entered the field of astronomy and many things are relatively simple to consider. If you have better ideas or suggestions, I hope you can provide help.Thank you very much.

**Comment by zpleunis** [comment]
Dear @frbliaker, 

This information is currently not publicly available, but we'll discuss within the collaboration if and how we can make this accessible in the future. For now, I've provided the average exposure in five declination bins that might be useful for your purposes, see: https://github.com/chime-frb-open-data/community/issues/95#issuecomment-1613114796

Best,
Ziggy
