### ISSUE TITLE
Downloaded catalog CSV has 64 extra FRBs in it

### ISSUE THREAD

**Issue by cwjames1983** [chime-frb-open-data/community#90]
The interactive table for Catalog 1 has the expected FRBs in it (536 total). However, clicking "Catalog 1 as csv file" (https://storage.googleapis.com/chimefrb-dev.appspot.com/catalog1/chimefrbcat1.csv) produces 600 FRBs. I can find no literature reference to a revised catalog. What's going on?

## Expected Behavior

The link produces the actual 536 in Catalog 1, *or* there is a public note on the site explaining the difference, *and* the FRBs in that table have a column for "old" (i.e. in original 536) or "added" (one of the new 64).

## Current Behavior

Gives 600 FRBs, I think it's a superset of the original ones, but I'm not checking 536 by eye!

## Possible Solution

Revert to the original catalog OR explain the additions with the new column added to identify the changes. Preferably both however!

## Steps to Reproduce (for bugs)

1. Open this link: https://storage.googleapis.com/chimefrb-dev.appspot.com/catalog1/chimefrbcat1.csv
2. Count the number of lines
3.
4.

## Context

I had used that .csv assuming there would be an erratum to the Cat 1 paper explaining the difference. Now I am having to re-do my calculations using the original 536, and I have to copy-paste data from the online table. Both steps are utterly miserable. I also happen to know that at least 20 people from CHIME are aware of this issue after our telecon, nobody has gotten back to me...

## Your Environment

I'm using Chrome 112.0.5615.137 , but I think this is irrelevant.

**Comment by kiyo-masui** [comment]
The CSV files have 1 row per sub burst, not per burst. There are a handful of FRBs that are made up of multiple sub bursts (not to be confused with repeat bursts from repeaters), and we measure the properties for these separately and make separate entries. There should be an entry in each row to indicate which FRB the sub burst belongs to.

Let me know if this clears things up so I can close the issue.

**Comment by cwjames1983** [comment]
Ah, OK, this does clear it up, somehow I missed this. Thanks for clarifying Kiyoshi! Go ahead and close.
