### ISSUE TITLE
Request for exposure time records as a function of observation date

### ISSUE THREAD

**Issue by shotaro-yamasaki** [chime-frb-open-data/community#95]
Dear CHIME FRB team members,

I hope this email finds you well. My name is Shotaro, and I appreciate the outstanding work that went into compiling them.

As part of my analysis, I am examining the event rate of FRBs in a time-dependent manner. For this purpose, I kindly request your assistance in providing me with the exposure time records for each FRB as a function of the observation date (MJD). Specifically, I would like to obtain the cumulative upper (and hopefully lower too) transit exposure time that has been spent on each individual source, including both non-repeating and repeating ones listed in Catalog 1, corresponding to the given observation date (MJD). This information would also include any periods during which the equipment was shut down. If it is challenging or time-consuming to provide detailed exposure time records, even a record of the shutdown periods in MJD during the Catalog 1 period would be helpful.

I noticed a similar request made by others in early April ([#87](https://github.com/chime-frb-open-data/community/issues/87)), which remains unanswered. I would greatly appreciate any assistance you can provide. Thank you in advance for your attention, and I look forward to your response.

Best regards,
Shotaro

**Comment by zpleunis** [comment]
Dear Shotaro,

(I emailed you the same information, but I am also posting it here in case others are interested.)

I do not have the exact numbers you're asking for ready, i.e., the exposure towards each individual repeater over time or the exposure until the first detection of each repeater. To reproduce Fig. 11 from [CHIME/FRB Collaboration 2023](https://ui.adsabs.harvard.edu/abs/2023ApJ...947...83C/abstract), I've attached the _average_ exposure in five declination bins (and a sixth antipodal declination bin for declinations that we see twice per sidereal day). 

To use this data in Python, here's a code snippet:

```python
import numpy as np

fname = "frep_exp_5equalbins.npy.npz"

data = np.load(fname)

# UTC dates
plot_dates = data["plot_dates"]
# edges of the declination bins (from -11 to 90, there are two bins from 69.8 to 90 degrees, one for the upper and one for the lower (antipodal) transit)
decbins = data["decbins"]
# average daily exposure in a declination bin in minutes for the upper transit
exp_mins_u = data["exp_mins_u"]
# standard deviation of the daily exposure in a declination bin in minutes for the upper transit
std_mins_u = data["std_mins_u"]
# average daily exposure in a declination bin in minutes for the lower (antipodal) transit
exp_mins_l = data["exp_mins_l"]
# standard deviation of the daily exposure in a declination bin in minutes for the lower (antipodal) transit
std_mins_l = data["std_mins_l"]
```

You can then plot the cumulative daily exposure vs. the detection dates of the repeaters.

Let me know if you have any questions about this! I hope this will be helpful to your project.

We will also discuss within the CHIME/FRB collaboration if in the future we can make the daily exposure maps public. This would enable the calculation of the daily exposure towards any sky position, including the sky positions of known repeaters. I will let you know if/when these would be publicly available.

[frep_exp_5equalbins.npy.zip](https://github.com/chime-frb-open-data/community/files/11905754/frep_exp_5equalbins.npy.zip)

Best,
Ziggy
