### ISSUE TITLE
redshift not included in FRB Catalog file?

### ISSUE THREAD

**Issue by raindownworld** [chime-frb-open-data/community#97]
Dear CHIME/FRB members,

I hope this email finds you well. I'm Bruce, an undergraduate from ZJU who is doing some research using data about FRBs from your website. Please allow me begin with expressing my honest admiration and gratitude for your outstanding work in FRB observation. 

I'm writing to ask about the spectroscopic redshift of FRBs because I have to use them to estimate different DM components along sightline, with which I'll use to find DM of intra-cluster medium. Noticing that you haven't included such data in your CHIME/FRB Collaboration (2023) Catalog file, I'm wondering where I can get this data or if you have measured this parameter?

I would greatly appreciate your assistance and looking forward to your early reply!

Best regards,
Bruce

**Comment by zpleunis** [comment]
Dear Bruce,

Thank you for your kind words.

For a photometric or spectroscopic redshift measurement to be made it is necessary to identify the host galaxy (or optical afterglow, if it exists) of an FRB.

Unfortunately the angular resolution (~10 arcminutes) of the CHIME/FRB data in catalog 1 prohibits the unambiguous association of FRBs with host galaxies, so for those FRBs we have not been able to gather redshift measurements.

However, we have been able to localize a number of (nearby) repeating FRB sources to their host galaxies either with the use of better data from our telescope (the complex voltages measured at each antenna called "baseband data" that give ~1 arcminute angular resolution) or with the help of collaborators and telescope (arrays) with better even angular resolution. You can read about those in the following papers:
- https://ui.adsabs.harvard.edu/#abs/2020Natur.577..190M/abstract
- https://ui.adsabs.harvard.edu/#abs/2021ApJ...919L..24B/abstract
- https://ui.adsabs.harvard.edu/#abs/2022Natur.602..585K/abstract
- https://ui.adsabs.harvard.edu/#abs/2022ApJ...927L...3N/abstract
- https://ui.adsabs.harvard.edu/#abs/2023ApJ...950..134M/abstract
- https://ui.adsabs.harvard.edu/#abs/2023arXiv230402638I/abstract
- https://ui.adsabs.harvard.edu/#abs/2023ApJ...949L...3R/abstract

Furthermore, we are working on upgrading CHIME/FRB to a VLBI experiment with the addition of three "Outrigger" telescopes across North America. This will in theory give CHIME/FRB subarcsecond resolution for localizing FRBs upon detection. The prototype of this system was already able to measure the redshift of one apparently nonrepeating FRB: https://ui.adsabs.harvard.edu/#abs/2023arXiv230709502C/abstract

Good luck with your research project!

Ziggy

**Comment by zpleunis** [comment]
Here’s the recording of a talk at a recent workshop where Daniele Michilli nicely reviews the radio localizations of FRBs: https://m.youtube.com/watch?v=6cfDpskJgII&list=PLOCI5KOMM-U5GSIMGX5ZLakE2vemtoWvG&index=1&t=390s

**Comment by raindownworld** [comment]
Many thanks to your detailed reply and this will help me a lot!
